SHELL = pwsh.exe
.SHELLFLAGS = -Noprofile -Command
PROJECT_NAME = CSOL24H
PROJECT_PATH := $(shell (Get-Location).ToString() -replace("\\", "/"))
SOURCE_PATH = source
BUILD_PATH = build/test
MODULES = 
VPATH = source
